# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(679, 528)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 661, 341))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalSlider = QtWidgets.QSlider(self.tab)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 60, 500, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(540, 60, 31, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.tab)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(20, 130, 500, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.tab)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(20, 200, 500, 22))
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(540, 130, 31, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(540, 200, 31, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalSlider_4 = QtWidgets.QSlider(self.tab)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(20, 270, 500, 22))
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(540, 270, 31, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(50, 40, 201, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 231, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(50, 180, 221, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(50, 250, 241, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(580, 60, 56, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(580, 130, 56, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(580, 200, 56, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(580, 270, 56, 21))
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(540, 130, 31, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(580, 130, 56, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(580, 270, 56, 21))
        self.label_10.setObjectName("label_10")
        self.horizontalSlider_5 = QtWidgets.QSlider(self.tab_2)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(20, 270, 500, 22))
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(50, 40, 201, 16))
        self.label_11.setObjectName("label_11")
        self.horizontalSlider_6 = QtWidgets.QSlider(self.tab_2)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(20, 60, 500, 22))
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(540, 60, 31, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(50, 180, 221, 16))
        self.label_12.setObjectName("label_12")
        self.horizontalSlider_7 = QtWidgets.QSlider(self.tab_2)
        self.horizontalSlider_7.setGeometry(QtCore.QRect(20, 130, 500, 22))
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setObjectName("horizontalSlider_7")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(540, 270, 31, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalSlider_8 = QtWidgets.QSlider(self.tab_2)
        self.horizontalSlider_8.setGeometry(QtCore.QRect(20, 200, 500, 22))
        self.horizontalSlider_8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_8.setObjectName("horizontalSlider_8")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(580, 60, 56, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(50, 250, 241, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(540, 200, 31, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(50, 110, 231, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(580, 200, 56, 21))
        self.label_16.setObjectName("label_16")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(540, 130, 31, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(580, 130, 56, 21))
        self.label_17.setObjectName("label_17")
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setGeometry(QtCore.QRect(50, 40, 201, 16))
        self.label_19.setObjectName("label_19")
        self.horizontalSlider_10 = QtWidgets.QSlider(self.tab_3)
        self.horizontalSlider_10.setGeometry(QtCore.QRect(20, 60, 500, 22))
        self.horizontalSlider_10.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_10.setObjectName("horizontalSlider_10")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_10.setGeometry(QtCore.QRect(540, 60, 31, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalSlider_11 = QtWidgets.QSlider(self.tab_3)
        self.horizontalSlider_11.setGeometry(QtCore.QRect(20, 130, 500, 22))
        self.horizontalSlider_11.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_11.setObjectName("horizontalSlider_11")
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setGeometry(QtCore.QRect(580, 60, 56, 21))
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(50, 110, 231, 16))
        self.label_23.setObjectName("label_23")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(50, 40, 201, 16))
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(260, 40, 31, 20))
        self.label_20.setObjectName("label_20")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_11.setGeometry(QtCore.QRect(180, 40, 61, 21))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.tabWidget.addTab(self.tab_4, "")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(550, 450, 110, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 450, 110, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(40, 40, 91, 21))
        self.label_22.setObjectName("label_22")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(140, 40, 41, 21))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(190, 40, 31, 21))
        self.label_24.setObjectName("label_24")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(330, 40, 41, 21))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(230, 40, 91, 21))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(380, 40, 31, 21))
        self.label_26.setObjectName("label_26")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(500, 40, 53, 24))
        self.spinBox.setObjectName("spinBox")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(430, 40, 91, 21))
        self.label_27.setObjectName("label_27")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 679, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "加速時ギアアップケイデンス"))
        self.label_2.setText(_translate("MainWindow", "加速時ギアダウンケイデンス"))
        self.label_3.setText(_translate("MainWindow", "巡航時ギアアップケイデンス"))
        self.label_4.setText(_translate("MainWindow", "巡航時ギアダウンケイデンス"))
        self.label_5.setText(_translate("MainWindow", "回転/分"))
        self.label_6.setText(_translate("MainWindow", "回転/分"))
        self.label_7.setText(_translate("MainWindow", "回転/分"))
        self.label_8.setText(_translate("MainWindow", "回転/分"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "平地設定"))
        self.label_9.setText(_translate("MainWindow", "回転/分"))
        self.label_10.setText(_translate("MainWindow", "回転/分"))
        self.label_11.setText(_translate("MainWindow", "加速時ギアアップケイデンス"))
        self.label_12.setText(_translate("MainWindow", "巡航時ギアアップケイデンス"))
        self.label_13.setText(_translate("MainWindow", "回転/分"))
        self.label_14.setText(_translate("MainWindow", "巡航時ギアダウンケイデンス"))
        self.label_15.setText(_translate("MainWindow", "加速時ギアダウンケイデンス"))
        self.label_16.setText(_translate("MainWindow", "回転/分"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "登り設定"))
        self.label_17.setText(_translate("MainWindow", "回転/分"))
        self.label_19.setText(_translate("MainWindow", "ギアアップケイデンス"))
        self.label_21.setText(_translate("MainWindow", "回転/分"))
        self.label_23.setText(_translate("MainWindow", "ギアダウンケイデンス"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "下り設定"))
        self.label_18.setText(_translate("MainWindow", "停止モード基準速度"))
        self.label_20.setText(_translate("MainWindow", "km/h"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "停止設定"))
        self.pushButton.setText(_translate("MainWindow", "Send"))
        self.pushButton_2.setText(_translate("MainWindow", "Reset"))
        self.label_22.setText(_translate("MainWindow", "登り坂しきい値"))
        self.label_24.setText(_translate("MainWindow", "%"))
        self.label_25.setText(_translate("MainWindow", "下り坂しきい値"))
        self.label_26.setText(_translate("MainWindow", "%"))
        self.label_27.setText(_translate("MainWindow", "変速段数"))
        self.menuFile.setTitle(_translate("MainWindow", "file"))
        self.actionImport.setText(_translate("MainWindow", "import"))
        self.actionExport.setText(_translate("MainWindow", "export"))

