# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(679, 528)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 661, 341))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.sl1 = QtWidgets.QSlider(self.tab)
        self.sl1.setGeometry(QtCore.QRect(20, 60, 500, 22))
        self.sl1.setMinimum(10)
        self.sl1.setMaximum(200)
        self.sl1.setProperty("value", 100)
        self.sl1.setOrientation(QtCore.Qt.Horizontal)
        self.sl1.setObjectName("sl1")
        self.sl2 = QtWidgets.QSlider(self.tab)
        self.sl2.setGeometry(QtCore.QRect(20, 130, 500, 22))
        self.sl2.setMinimum(10)
        self.sl2.setMaximum(200)
        self.sl2.setProperty("value", 70)
        self.sl2.setOrientation(QtCore.Qt.Horizontal)
        self.sl2.setObjectName("sl2")
        self.sl3 = QtWidgets.QSlider(self.tab)
        self.sl3.setGeometry(QtCore.QRect(20, 200, 500, 22))
        self.sl3.setMinimum(10)
        self.sl3.setMaximum(200)
        self.sl3.setProperty("value", 110)
        self.sl3.setOrientation(QtCore.Qt.Horizontal)
        self.sl3.setObjectName("sl3")
        self.sl4 = QtWidgets.QSlider(self.tab)
        self.sl4.setGeometry(QtCore.QRect(20, 270, 500, 22))
        self.sl4.setMinimum(10)
        self.sl4.setMaximum(200)
        self.sl4.setProperty("value", 85)
        self.sl4.setOrientation(QtCore.Qt.Horizontal)
        self.sl4.setObjectName("sl4")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(50, 40, 201, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 231, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(50, 180, 221, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(50, 250, 241, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(580, 60, 56, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(580, 130, 56, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(580, 200, 56, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(580, 270, 56, 21))
        self.label_8.setObjectName("label_8")
        self.sp1 = QtWidgets.QSpinBox(self.tab)
        self.sp1.setGeometry(QtCore.QRect(530, 60, 50, 24))
        self.sp1.setMinimum(10)
        self.sp1.setMaximum(200)
        self.sp1.setProperty("value", 100)
        self.sp1.setObjectName("sp1")
        self.sp2 = QtWidgets.QSpinBox(self.tab)
        self.sp2.setGeometry(QtCore.QRect(530, 130, 50, 24))
        self.sp2.setMinimum(10)
        self.sp2.setMaximum(200)
        self.sp2.setProperty("value", 70)
        self.sp2.setObjectName("sp2")
        self.sp3 = QtWidgets.QSpinBox(self.tab)
        self.sp3.setGeometry(QtCore.QRect(530, 200, 50, 24))
        self.sp3.setMinimum(10)
        self.sp3.setMaximum(200)
        self.sp3.setProperty("value", 110)
        self.sp3.setObjectName("sp3")
        self.sp4 = QtWidgets.QSpinBox(self.tab)
        self.sp4.setGeometry(QtCore.QRect(530, 270, 50, 24))
        self.sp4.setMinimum(10)
        self.sp4.setMaximum(200)
        self.sp4.setProperty("value", 85)
        self.sp4.setObjectName("sp4")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(580, 130, 56, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(580, 270, 56, 21))
        self.label_10.setObjectName("label_10")
        self.sl8 = QtWidgets.QSlider(self.tab_2)
        self.sl8.setGeometry(QtCore.QRect(20, 270, 500, 22))
        self.sl8.setMinimum(10)
        self.sl8.setMaximum(200)
        self.sl8.setProperty("value", 65)
        self.sl8.setOrientation(QtCore.Qt.Horizontal)
        self.sl8.setObjectName("sl8")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(50, 40, 201, 16))
        self.label_11.setObjectName("label_11")
        self.sl5 = QtWidgets.QSlider(self.tab_2)
        self.sl5.setGeometry(QtCore.QRect(20, 60, 500, 22))
        self.sl5.setMinimum(10)
        self.sl5.setMaximum(200)
        self.sl5.setProperty("value", 90)
        self.sl5.setOrientation(QtCore.Qt.Horizontal)
        self.sl5.setObjectName("sl5")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(50, 180, 221, 16))
        self.label_12.setObjectName("label_12")
        self.sl6 = QtWidgets.QSlider(self.tab_2)
        self.sl6.setGeometry(QtCore.QRect(20, 130, 500, 22))
        self.sl6.setMinimum(10)
        self.sl6.setMaximum(200)
        self.sl6.setProperty("value", 65)
        self.sl6.setOrientation(QtCore.Qt.Horizontal)
        self.sl6.setObjectName("sl6")
        self.sl7 = QtWidgets.QSlider(self.tab_2)
        self.sl7.setGeometry(QtCore.QRect(20, 200, 500, 22))
        self.sl7.setMinimum(10)
        self.sl7.setMaximum(200)
        self.sl7.setProperty("value", 90)
        self.sl7.setOrientation(QtCore.Qt.Horizontal)
        self.sl7.setObjectName("sl7")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(580, 60, 56, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(50, 250, 241, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(50, 110, 231, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(580, 200, 56, 21))
        self.label_16.setObjectName("label_16")
        self.sp5 = QtWidgets.QSpinBox(self.tab_2)
        self.sp5.setGeometry(QtCore.QRect(530, 60, 50, 24))
        self.sp5.setMinimum(10)
        self.sp5.setMaximum(200)
        self.sp5.setProperty("value", 90)
        self.sp5.setObjectName("sp5")
        self.sp6 = QtWidgets.QSpinBox(self.tab_2)
        self.sp6.setGeometry(QtCore.QRect(530, 130, 50, 24))
        self.sp6.setMinimum(10)
        self.sp6.setMaximum(200)
        self.sp6.setProperty("value", 65)
        self.sp6.setObjectName("sp6")
        self.sp7 = QtWidgets.QSpinBox(self.tab_2)
        self.sp7.setGeometry(QtCore.QRect(530, 200, 50, 24))
        self.sp7.setMinimum(10)
        self.sp7.setMaximum(200)
        self.sp7.setProperty("value", 90)
        self.sp7.setObjectName("sp7")
        self.sp8 = QtWidgets.QSpinBox(self.tab_2)
        self.sp8.setGeometry(QtCore.QRect(530, 270, 50, 24))
        self.sp8.setMinimum(10)
        self.sp8.setMaximum(200)
        self.sp8.setProperty("value", 65)
        self.sp8.setObjectName("sp8")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(580, 130, 56, 21))
        self.label_17.setObjectName("label_17")
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setGeometry(QtCore.QRect(50, 40, 201, 16))
        self.label_19.setObjectName("label_19")
        self.sl9 = QtWidgets.QSlider(self.tab_3)
        self.sl9.setGeometry(QtCore.QRect(20, 60, 500, 22))
        self.sl9.setMinimum(10)
        self.sl9.setMaximum(200)
        self.sl9.setProperty("value", 80)
        self.sl9.setOrientation(QtCore.Qt.Horizontal)
        self.sl9.setObjectName("sl9")
        self.sl10 = QtWidgets.QSlider(self.tab_3)
        self.sl10.setGeometry(QtCore.QRect(20, 130, 500, 22))
        self.sl10.setMinimum(10)
        self.sl10.setMaximum(200)
        self.sl10.setProperty("value", 50)
        self.sl10.setOrientation(QtCore.Qt.Horizontal)
        self.sl10.setObjectName("sl10")
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setGeometry(QtCore.QRect(580, 60, 56, 21))
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(50, 110, 231, 16))
        self.label_23.setObjectName("label_23")
        self.sp9 = QtWidgets.QSpinBox(self.tab_3)
        self.sp9.setGeometry(QtCore.QRect(530, 60, 50, 24))
        self.sp9.setMinimum(10)
        self.sp9.setMaximum(200)
        self.sp9.setProperty("value", 80)
        self.sp9.setObjectName("sp9")
        self.sp10 = QtWidgets.QSpinBox(self.tab_3)
        self.sp10.setGeometry(QtCore.QRect(530, 130, 50, 24))
        self.sp10.setMinimum(10)
        self.sp10.setMaximum(200)
        self.sp10.setProperty("value", 50)
        self.sp10.setObjectName("sp10")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(50, 40, 201, 16))
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(260, 40, 31, 20))
        self.label_20.setObjectName("label_20")
        self.sp11 = QtWidgets.QSpinBox(self.tab_4)
        self.sp11.setGeometry(QtCore.QRect(180, 33, 81, 31))
        self.sp11.setMinimum(10)
        self.sp11.setMaximum(200)
        self.sp11.setProperty("value", 15)
        self.sp11.setObjectName("sp11")
        self.tabWidget.addTab(self.tab_4, "")
        self.send_button = QtWidgets.QPushButton(self.centralwidget)
        self.send_button.setGeometry(QtCore.QRect(550, 450, 110, 32))
        self.send_button.setObjectName("send_button")
        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_button.setGeometry(QtCore.QRect(440, 450, 110, 32))
        self.reset_button.setObjectName("reset_button")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(20, 40, 91, 21))
        self.label_22.setObjectName("label_22")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(170, 40, 31, 21))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(200, 40, 91, 21))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(350, 40, 31, 21))
        self.label_26.setObjectName("label_26")
        self.sp14 = QtWidgets.QSpinBox(self.centralwidget)
        self.sp14.setGeometry(QtCore.QRect(450, 33, 53, 31))
        self.sp14.setMinimum(1)
        self.sp14.setMaximum(15)
        self.sp14.setProperty("value", 10)
        self.sp14.setObjectName("sp14")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(380, 40, 91, 21))
        self.label_27.setObjectName("label_27")
        self.port = QtWidgets.QComboBox(self.centralwidget)
        self.port.setGeometry(QtCore.QRect(553, 35, 121, 31))
        self.port.setObjectName("port")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(510, 40, 51, 21))
        self.label_28.setObjectName("label_28")
        self.sp12 = QtWidgets.QSpinBox(self.centralwidget)
        self.sp12.setGeometry(QtCore.QRect(120, 33, 50, 31))
        self.sp12.setMinimum(1)
        self.sp12.setMaximum(100)
        self.sp12.setProperty("value", 5)
        self.sp12.setObjectName("sp12")
        self.sp13 = QtWidgets.QSpinBox(self.centralwidget)
        self.sp13.setGeometry(QtCore.QRect(300, 33, 50, 31))
        self.sp13.setMinimum(1)
        self.sp13.setMaximum(100)
        self.sp13.setProperty("value", 5)
        self.sp13.setObjectName("sp13")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 679, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AT_Config_Tool"))
        self.label.setText(_translate("MainWindow", "加速時ギアアップケイデンス"))
        self.label_2.setText(_translate("MainWindow", "加速時ギアダウンケイデンス"))
        self.label_3.setText(_translate("MainWindow", "巡航時ギアアップケイデンス"))
        self.label_4.setText(_translate("MainWindow", "巡航時ギアダウンケイデンス"))
        self.label_5.setText(_translate("MainWindow", "回転/分"))
        self.label_6.setText(_translate("MainWindow", "回転/分"))
        self.label_7.setText(_translate("MainWindow", "回転/分"))
        self.label_8.setText(_translate("MainWindow", "回転/分"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "平地設定"))
        self.label_9.setText(_translate("MainWindow", "回転/分"))
        self.label_10.setText(_translate("MainWindow", "回転/分"))
        self.label_11.setText(_translate("MainWindow", "加速時ギアアップケイデンス"))
        self.label_12.setText(_translate("MainWindow", "巡航時ギアアップケイデンス"))
        self.label_13.setText(_translate("MainWindow", "回転/分"))
        self.label_14.setText(_translate("MainWindow", "巡航時ギアダウンケイデンス"))
        self.label_15.setText(_translate("MainWindow", "加速時ギアダウンケイデンス"))
        self.label_16.setText(_translate("MainWindow", "回転/分"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "登り設定"))
        self.label_17.setText(_translate("MainWindow", "回転/分"))
        self.label_19.setText(_translate("MainWindow", "ギアアップケイデンス"))
        self.label_21.setText(_translate("MainWindow", "回転/分"))
        self.label_23.setText(_translate("MainWindow", "ギアダウンケイデンス"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "下り設定"))
        self.label_18.setText(_translate("MainWindow", "停止モード基準速度"))
        self.label_20.setText(_translate("MainWindow", "km/h"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "停止設定"))
        self.send_button.setText(_translate("MainWindow", "Send"))
        self.reset_button.setText(_translate("MainWindow", "Reset"))
        self.label_22.setText(_translate("MainWindow", "登り坂しきい値"))
        self.label_24.setText(_translate("MainWindow", "%"))
        self.label_25.setText(_translate("MainWindow", "下り坂しきい値"))
        self.label_26.setText(_translate("MainWindow", "%"))
        self.label_27.setText(_translate("MainWindow", "変速段数"))
        self.label_28.setText(_translate("MainWindow", "ポート"))
        self.menuFile.setTitle(_translate("MainWindow", "file"))
        self.actionImport.setText(_translate("MainWindow", "import"))
        self.actionExport.setText(_translate("MainWindow", "export"))

